-- If travelvoo.in and demo.travelvoo.in showed the same tenant, the apex was often stored as
-- custom_domain on a tenant row. The app treats platform_base_domain / NEXT_PUBLIC_PLATFORM_BASE_DOMAIN
-- as marketing-only; still run this once to clean bad rows.
--
-- Review first:
-- SELECT id, tenant_id, subdomain, custom_domain FROM public.tenant_domains WHERE custom_domain IN ('travelvoo.in', 'www.travelvoo.in');
--
-- Then clear apex from tenant custom_domain (adjust host if needed):
-- UPDATE public.tenant_domains
-- SET custom_domain = ''
-- WHERE lower(trim(custom_domain)) IN ('travelvoo.in', 'www.travelvoo.in');
